# Generated by Django 4.0.1 on 2022-04-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('register_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=30)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('exam_date', models.DateTimeField()),
                ('Marks', models.IntegerField()),
                ('Grade', models.CharField(max_length=10)),
            ],
        ),
    ]
